create table AUDIT_EVENT (AUDIT_EVENT_ID NUMBER(30, 0) not null, LOGICAL_GROUP_ID NUMBER(30, 0), TARGET_ENTITY_ID NUMBER(30, 0) not null, EVENT_TYPE varchar2(255 char) not null, AUDIT_TYPE_ID NUMBER(30, 0) not null, AUDIT_TRANSACTION_ID NUMBER(30, 0) not null, constraint PK_AUDIT_EVENT primary key (AUDIT_EVENT_ID));
create table AUDIT_EVENT_PAIR (IS_COLLECTION char(1 char) not null, AUDIT_EVENT_PAIR_ID NUMBER(30, 0) not null, STRING_VALUE varchar2(3000 char), AUDIT_EVENT_ID NUMBER(30, 0) not null, AUDIT_TYPE_FIELD_ID NUMBER(30, 0) not null, constraint PK_AUDIT_EVENT_PAIR primary key (AUDIT_EVENT_PAIR_ID));
create table AUDIT_EVENT_PAIR_COLLECTION (AUDIT_EVENT_PAIR_ID NUMBER(30, 0) not null, COLLECTION_ENTITY_ID number(19,0) not null);
create table AUDIT_TRANSACTION (AUDIT_TRANSACTION_ID NUMBER(30, 0) not null, TRANSACTION_TMSTP timestamp not null, TRANSACTION_USER varchar2(255 char), constraint PK_AUDIT_TRANSACTION primary key (AUDIT_TRANSACTION_ID));
create table AUDIT_TYPE (DTYPE char(1 char) not null, AUDIT_TYPE_ID NUMBER(30, 0) not null, CLASS_NAME varchar2(255 char) not null, LABEL varchar2(255 char), ENTITY_ID_CLASS_NAME varchar2(255 char), COLLECTION_CLASS_NAME varchar2(255 char), constraint PK_AUDIT_TYPE primary key (AUDIT_TYPE_ID));
create table AUDIT_TYPE_FIELD (AUDIT_TYPE_FIELD_ID NUMBER(30, 0) not null, LABEL varchar2(255 char), FIELD_NAME varchar2(255 char) not null, AUDIT_TYPE_ID NUMBER(30, 0) not null, constraint PK_AUDIT_TYPE_FIELD primary key (AUDIT_TYPE_FIELD_ID));
alter table AUDIT_EVENT add constraint FK_AUDIT_TRANSACTION_EVENT foreign key (AUDIT_TRANSACTION_ID) references AUDIT_TRANSACTION;
alter table AUDIT_EVENT add constraint FK_AUDIT_TYPE_EVENT foreign key (AUDIT_TYPE_ID) references AUDIT_TYPE;
alter table AUDIT_EVENT_PAIR add constraint FK_AUDIT_EVENT_PAIR foreign key (AUDIT_EVENT_ID) references AUDIT_EVENT;
alter table AUDIT_EVENT_PAIR add constraint FK_AUDIT_TYPE_FIELD_EVNT_PAIR foreign key (AUDIT_TYPE_FIELD_ID) references AUDIT_TYPE_FIELD;
alter table AUDIT_EVENT_PAIR_COLLECTION add constraint FK_AUDIT_EVENT_PAIR_COLLECTION foreign key (AUDIT_EVENT_PAIR_ID) references AUDIT_EVENT_PAIR;
alter table AUDIT_TYPE_FIELD add constraint FK_AUDIT_TYPE_FIELD foreign key (AUDIT_TYPE_ID) references AUDIT_TYPE;
create sequence AUDIT_EVENT_PAIR_SEQ;
create sequence AUDIT_EVENT_SEQ;
create sequence AUDIT_TRANSACTION_SEQ;
create sequence AUDIT_TYPE_FIELD_SEQ;
create sequence AUDIT_TYPE_SEQ;
