DROP TABLE AUDIT_CLASS CASCADE CONSTRAINTS;
DROP TABLE AUDIT_CLASS_FIELD CASCADE CONSTRAINTS;
DROP TABLE AUDIT_EVENT CASCADE CONSTRAINTS;
DROP TABLE AUDIT_EVENT_PAIR CASCADE CONSTRAINTS;
DROP TABLE AUDIT_EVENT_PAIR_COLLECTION CASCADE CONSTRAINTS;
DROP TABLE AUDIT_TRANSACTION CASCADE CONSTRAINTS;
